apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-project-a
  namespace: argocd
spec:
  project: demo-platform
  sources:
    - repoURL: https://github.com/MohamedHamdy404/gitops-demo-project-a.git
      path: nginx
      targetRevision: main
      helm:
        valueFiles:
          - $values/values/project-a/prod-values.yaml
    - repoURL: https://github.com/MohamedHamdy404/gitops-demo-argocd-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-project-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
