apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-project-c
  namespace: argocd
spec:
  project: demo-platform
  sources:
  - repoURL: https://github.com/MohamedHamdy404/gitops-demo-project-c.git
    path: postgresql
    targetRevision: main
    helm:
      valueFiles:
      - $values/values/project-c/prod-values.yaml
  - repoURL: https://github.com/MohamedHamdy404/gitops-demo-argocd-gitops.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-project-c
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
