image:
  registry: docker.io
  repository: bitnamilegacy/redis

sentinel:
  image:
    registry: docker.io
    repository: bitnamilegacy/redis-sentinel

metrics:
  image:
    registry: docker.io
    repository: bitnamilegacy/redis-exporter

volumePermissions:
  image:
    registry: docker.io
    repository: bitnamilegacy/os-shell

sysctlImage:
  registry: docker.io
  repository: bitnamilegacy/os-shell
  
master:
  persistence:
    enabled: true
    size: 1Gi
replica:
  replicaCount: 3
  persistence:
    enabled: true
    size: 1Gi
sentinel:
  enabled: true
