apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-project-b
  namespace: argocd
spec:
  project: demo-platform
  sources:
    - repoURL: https://github.com/MohamedHamdy404/gitops-demo-project-b.git
      path: redis
      targetRevision: main
      helm:
        valueFiles:
          - $values/values/project-b/dev-values.yaml
    - repoURL: https://github.com/MohamedHamdy404/gitops-demo-argocd-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-project-b
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
